services:       
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    environment:
      PUID: 1000 # optional, your user id
      PGID: 1000 # optional, your group id
    volumes:
      - ${ARRPATH}homepage/config:/app/config
      - ${ARRPATH}homepage/icons:/app/public/icons
      - ${ARRPATH}homepage/data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    ports:
      - '3000:3000'
    env_file:
      - '.env'

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    ports:
      - '5055:5055'   # Jellyseerr web interface
    volumes:
      - ${ARRPATH}jellyseerr/config:/app/config
    env_file:
      - '.env'
    restart: unless-stopped

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 1000:1000
    volumes:
      - ${ARRPATH}maintainerr/data:/opt/data
    environment:
      - TZ=Europe/Brussels
      # - DEBUG=true # Uncomment to enable debug logs
    ports:
      - '6246:6246'
    restart: unless-stopped

# ██████╗ ██████╗  ██████╗ ██╗    ██╗██╗      █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔═══██╗██║    ██║██║     ██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝██████╔╝██║   ██║██║ █╗ ██║██║     ███████║██████╔╝██████╔╝
# ██╔═══╝ ██╔══██╗██║   ██║██║███╗██║██║     ██╔══██║██╔══██╗██╔══██╗
# ██║     ██║  ██║╚██████╔╝╚███╔███╔╝███████╗██║  ██║██║  ██║██║  ██║
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═
                              
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${ARRPATH}prowlarr/config:/config
      - ${ARRPATH}prowlarr/backup:/data/Backup
      - ${ARRPATH}downloads:/downloads
    ports:
      - 9696:9696
    restart: unless-stopped
    env_file:
      - '.env'
      
# ███████╗ ██████╗ ███╗   ██╗ █████╗ ██████╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔══██╗██╔══██╗██╔══██╗
# ███████╗██║   ██║██╔██╗ ██║███████║██████╔╝██████╔╝
# ╚════██║██║   ██║██║╚██╗██║██╔══██║██╔══██╗██╔══██╗
# ███████║╚██████╔╝██║ ╚████║██║  ██║██║  ██║██║  ██║
# ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                                 
      
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${ARRPATH}sonarr/config:/config
      - ${ARRPATH}sonarr/backup:/data/Backup
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗  █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝                                              

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - ${ARRPATH}radarr/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}radarr/backup:/data/Backup
      - ${ARRPATH}downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██╗     ██╗██████╗  █████╗ ██████╗ ██████╗ 
# ██║     ██║██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██║     ██║██║  ██║███████║██████╔╝██████╔╝
# ██║     ██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ███████╗██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚══════╝╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                             
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${ARRPATH}lidarr/config:/config
      - ${ARRPATH}lidarr/music:/data/musicfolder
      - ${ARRPATH}downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    env_file:
      - '.env'
      
# ██████╗ ███████╗ █████╗ ██████╗  █████╗ ██████╗ ██████╗ 
# ██╔══██╗██╔════╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗
# ██████╔╝█████╗  ███████║██║  ██║███████║██████╔╝██████╔╝
# ██╔══██╗██╔══╝  ██╔══██║██║  ██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║███████╗██║  ██║██████╔╝██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
                                                                                                                   
  # readarr:
  #   image: linuxserver/readarr:develop
  #   container_name: readarr
  #   hostname: readarr
  #   volumes:
  #     - ${ARRPATH}readarr/config:/config
  #     - ${ARRPATH}readarr/books:/data/books
  #     - ${ARRPATH}downloads:/downloads
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped
  #   env_file:
  #     - '.env'

# ██╗  ██╗ ██████╗ ███╗   ███╗ █████╗ ██████╗ ██████╗ 
# ██║  ██║██╔═══██╗████╗ ████║██╔══██╗██╔══██╗██╔══██╗
# ███████║██║   ██║██╔████╔██║███████║██████╔╝██████╔╝
# ██╔══██║██║   ██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██╗
# ██║  ██║╚██████╔╝██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║
# ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝
        
  # homarr:
  #   container_name: homarr
  #   image: ghcr.io/ajnart/homarr:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ${ARRPATH}homarr/configs:/app/data/configs
  #     - ${ARRPATH}homarr/icons:/app/public/icons
  #     - ${ARRPATH}homarr/data:/data
  #   ports:
  #     - '7575:7575'
  #   env_file:
  #     - '.env'

#      ██╗███████╗██╗     ██╗  ██╗   ██╗███████╗██╗███╗   ██╗
#      ██║██╔════╝██║     ██║  ╚██╗ ██╔╝██╔════╝██║████╗  ██║
#      ██║█████╗  ██║     ██║   ╚████╔╝ █████╗  ██║██╔██╗ ██║
# ██   ██║██╔══╝  ██║     ██║    ╚██╔╝  ██╔══╝  ██║██║╚██╗██║
# ╚█████╔╝███████╗███████╗███████╗██║   ██║     ██║██║ ╚████║
#  ╚════╝ ╚══════╝╚══════╝╚══════╝╚═╝   ╚═╝     ╚═╝╚═╝  ╚═══╝
     
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    volumes:
      - ${ARRPATH}jellyfin/config:/config
      - ${ARRPATH}radarr/movies:/data/Movies
      - ${ARRPATH}sonarr/tvshows:/data/TVShows
      - ${ARRPATH}lidarr/music:/data/Music
      - ${ARRPATH}readarr/books:/data/Books
    env_file:
      - '.env'
    restart: unless-stopped
          
  # emby:
  #   image: linuxserver/emby
  #   container_name: emby
  #   ports:
  #     - '8097:8096/tcp'   # Emby web interface
  #     - '8920:8920/tcp'   # Secure connection (HTTPS)
  #     - '7360:7359/udp'   # Network discovery
  #     - '1901:1900/udp'   # DLNA port
  #   volumes:
  #     - ${ARRPATH}emby/config:/config
  #     - ${ARRPATH}radarr/movies:/data/Movies
  #     - ${ARRPATH}sonarr/tvshows:/data/TVShows
  #     - ${ARRPATH}lidarr/music:/data/Music
  #     - ${ARRPATH}readarr/books:/data/Books
  #   env_file:
  #     - '.env'
  #   restart: unless-stopped
#  ██████╗ ██████╗ ██╗████████╗████████╗ ██████╗ ██████╗ ██████╗ ███████╗███╗   ██╗████████╗
# ██╔═══██╗██╔══██╗██║╚══██╔══╝╚══██╔══╝██╔═══██╗██╔══██╗██╔══██╗██╔════╝████╗  ██║╚══██╔══╝
# ██║   ██║██████╔╝██║   ██║      ██║   ██║   ██║██████╔╝██████╔╝█████╗  ██╔██╗ ██║   ██║   
# ██║▄▄ ██║██╔══██╗██║   ██║      ██║   ██║   ██║██╔══██╗██╔══██╗██╔══╝  ██║╚██╗██║   ██║   
# ╚██████╔╝██████╔╝██║   ██║      ██║   ╚██████╔╝██║  ██║██║  ██║███████╗██║ ╚████║   ██║   
#  ╚══▀▀═╝ ╚═════╝ ╚═╝   ╚═╝      ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝                                                                                          
                                                                                             
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    healthcheck:
      start_period: 15s
    env_file:
      - '.env'
